### ISSUE TITLE
chart.events object is always empty

### ISSUE THREAD

**Issue by jyve** [daemth/easychart#11]
in the 'appleWatch' template, there are some functions in the chart.events object. However in the config returned by the configUpdate event, the chart.events object is always empty.

**Comment by daemth** [comment]
Can this even be fixed without storing a reference between a chosen template and the final chart-result (as the charts-event-formatters can be adjusted through the customize-screen)?

**Comment by frankbaele** [comment]
hi, this problem is just a relocation of an old problem with the json parsing and loosing function in the process(and using eval while importing).

Maybe we should take a look into -> [jsonfn](https://github.com/vkiryukhin/jsonfn)

**Comment by frankbaele** [comment]
the api has been extended with setConfigStringified and getConfigStringified, who allow you to get and set the config object already stringified.

This is specific for the usecase where there are functions in the config and the config object is stringified as part of beeing imported in to a database.

**Comment by frankbaele** [comment]
Another impact of this change is that template.js has been reverted to a json file for development sanity sake.

**Comment by frankbaele** [comment]
an exmaple can be found in the [demo](demo/index.html)

**Comment by daemth** [comment]
icons disappeared and faulty series name position

**Comment by frankbaele** [comment]
yes, this advanced behavior requires the usage of 

setConfigStringified()
getConfigStringified()

Just tested this locally and it works perfect
