### ISSUE TITLE
Is it possible to refresh the preview in the editor?

### ISSUE THREAD

**Issue by monbro** [daemth/easychart#14]
Hi, 
I am setting my data and config from outside via `ec.setConfig(config)` and `ec.setData(config)`. Then when I am opening my bootstrap modal window where the easychart editor is included, the data and config is set correct, but the highcharts preview box on the right (`<div id="chartContainer">...</div>`) was not being updated.

Can I call a function to force an update on it?

Thank you!
Michael

**Comment by monbro** [comment]
Ah I think this was a fault by me, I did not properly set the data and config.

**Comment by frankbaele** [comment]
Ok easy Fix, thx for closing

**Comment by monbro** [comment]
Ah sorry I have to reopen it :) 

I do set the data and the config. But it will show the preview and datatable from the last chart I was editing. Only as soon as I edit a field in the data table it will update the datatable and the preview to the correct / current chart.

Any idea what this could be?

**Comment by monbro** [comment]
I think there is a trigger missing somehwere, when the data or the config is being updated from outside.

**Comment by frankbaele** [comment]
So you are reusing the same instance? just setting different config and data when the modal opens?

any chance for jsfiddle? that would facilitate allot

**Comment by frankbaele** [comment]
What part of your graph was incorrect? the data or the config?

**Comment by frankbaele** [comment]
because https://github.com/bestuurszaken/easychart/blob/master/src/js/services/data.js#L67 will trigger an update event that will trigger the config update->
https://github.com/bestuurszaken/easychart/blob/master/src/js/services/config.js#L202
But an set
https://github.com/bestuurszaken/easychart/blob/master/src/js/services/config.js#L48
will not trigger an update, so im guessing if i add and config update there it will be fixed

**Comment by monbro** [comment]
Yes this seems to be one part of the problem. When I do update the data after setting the config, the highcharts preview div chartContainer is correct. I suggest to add a update trigger to the config set method as well.

So this way the config and data should be updated and the event distributed within easycharts. But sometimes it seems it does still not pick the change up.

---

The other part of the problem is, that handsontable (which I heavily assume) is not refreshing the view of the table as it is not visible in the browser when the data is updated --> as I am using a modal window (via twitter bootstap js). 

---

Overall I solved both problems by adding a function "triggerUdpate" to the API which will trigger the dataUpdate event to the mediator:

``` 
that.triggerUpdate = function () {
          var data = that.get();
          mediator.trigger('dataUpdate', data);
};
```

And then I add an event to my modal, that as soon as its showed it will trigger the update:

````
$('#easyChartModal').on('shown.bs.modal', function (e) {
      easychartInstance.triggerUpdate();
    });
````

Which will update the highcharts preview div and the datatables correctly.

**Comment by monbro** [comment]
Its up to you if you want to close this task or to keep it open for further process on this.

**Comment by frankbaele** [comment]
I rather fix the core issue of this.

**Comment by frankbaele** [comment]
the config update fix fixed the essential part and the issue with handsontable seem to be not related to the project. Because we are doing the proper data update in code.
