### ISSUE TITLE
Separation of source types

### ISSUE THREAD

**Issue by AndreKkl** [daemth/easychart#15]
Hey,
some wouldn't say it's an issue but it definitely is: It's easy to see your love to nodejs and javascript but it's an design issue to combine everything in javascript to finally spit it out.
A more welcome separation would at least consider separate css and not a single but bloated javascript file that includes markup, styling and scripting. 

I know it's working but it's absolutely unnecessary, makes it harder to customize and does not follow any guideline for separation of different contents. Only because it's possible it doesn't mean that it's a good way.

Please consider in the future a better concept that separates javascript, css and maybe a html-template for the html markup that  will be used by your nodejs scripts. It would help to widespread your very cool tool and to gain acceptance.

Best regards

**Comment by monbro** [comment]
I agree, 

independent of the these arguments I think its always good to look how bigger communities and projects are managing their source. https://cdnjs.com/libraries/jqueryui for example also split out the css in their distribution. 

Another argument would be the loading priority / performance, so css files are loaded (and might be concatenated) on the top of a html page and the javascript on the bottom.

**Comment by frankbaele** [comment]
I can agree on the css being included is maybe pushing it a bit to far and I recently stopped  doing this.

As for the template, we just wanted to get a new version out and working as fast as possible. We could have used templates that facilitated the later alteration/styling of the application but didn't want to bother with it at that time.

I'm keeping this issue open until both issues (css and html templates) are resolved.

**Comment by frankbaele** [comment]
Hi, we are working on a new version that will have separate css and templates.
The css extraction was the first commit of the new branch templates will be supported by our migration to vue.js .
Feel free to take a look at the new 4.x branch in the future.
