### ISSUE TITLE
Questions / Support

### ISSUE THREAD

**Issue by jhallam3** [daemth/easychart#22]
Hi, 

Firstly what a great product!

Im very keen to use this in some software I'm in the middle of build. at present Im building the charts manually and thats long winded.

The aim is to use your EasyChart to allow users to modify the chart with ease.

so have some question. 

How can I show a chart that users EasyChart to pull the data from a URL and then show it to the page? 

How can I save what the user has modified? 

Im lost really within the documentation, not sure where to start. 

An example would be awesome. Ideal would be to have a chart on a page with a spanner symbol then click that, this will load the EasyChart JS page. ("easyChart/demo/index.html") then make the change, hit save and its then rendered on the page for all users to see.

**Comment by daemth** [comment]
What kind of example do you need? Are you building a Drupal-project?

**Comment by jhallam3** [comment]
HI thanks for coming back to me.
It's based in C# MVC but that's no issue

A HTML page that shows a chart where it's got a settings option where I can
click that to modify the the graph from say a bar chart to a pie chart
click save and its then saved it on the page. Does that make sense?

Regards

Jon Hallam


On 8 Sep 2016, at 17:32, Thomas Daem <notifications@github.com> wrote:

What kind of example do you need? Are you building a Drupal-project?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bestuurszaken/easychart/issues/22#issuecomment-245656885>,
or mute the thread

**Comment by daemth** [comment]
Yes it does, I'll work something out for you asap.

**Comment by jhallam3** [comment]
Thanks the data needs to be from a URL. That data will come from a URL with
the changing every 1 minute or less. Is that still workable?

Regards

Jon Hallam


On 8 Sep 2016, at 18:36, Thomas Daem <notifications@github.com> wrote:

Yes it does, I'll work something out for you asap.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bestuurszaken/easychart/issues/22#issuecomment-245676834>,
or mute the thread

**Comment by daemth** [comment]
Yes.

**Comment by jhallam3** [comment]
Also there's multiple graphs per page. Hope that's not an issue

Regards

Jon Hallam


On 8 Sep 2016, at 18:36, Thomas Daem <notifications@github.com> wrote:

Yes it does, I'll work something out for you asap.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bestuurszaken/easychart/issues/22#issuecomment-245676834>,
or mute the thread

**Comment by jhallam3** [comment]
Hi, I'm happy to pay for your time if that will speed the example I'm
looking for?

Regards

Jon Hallam


On 8 Sep 2016, at 18:44, Thomas Daem <notifications@github.com> wrote:

Yes.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bestuurszaken/easychart/issues/22#issuecomment-245679290>,
or mute the thread

**Comment by daemth** [comment]
opened feature request #27

**Comment by daemth** [comment]
lots of progression made in this, hold on a few more days! ;-)

**Comment by jhallam3** [comment]
Awesome !!.

Regards

Jon Hallam


On 21 Sep 2016, at 21:06, Thomas Daem <notifications@github.com> wrote:

lots of progression made in this, hold on a few more days! ;-)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/daemth/easychart/issues/22#issuecomment-248727115>, or mute
the thread

**Comment by jhallam3** [comment]
Hi, 

How you getting on this with? 

Would be great to get it for the weekend. :)

Thanks in advance. 

Jon

**Comment by daemth** [comment]
@frankbaele will review #38 asap. In the meantime feel free to checkout https://github.com/daemth/easychart/tree/feature/issue-27__UIMode-option and experiment with our new UIMode-option. I don't think there will be anymore functional changes on this.
After review I'll extend the demo towards your use-case.

**Comment by jhallam3** [comment]
Hi,

Been working on this today. 

Is there a way of removing the header to the chart? I need to just see the chart rather than the header.

**Comment by daemth** [comment]
Can you show (printscreen) the header you want to get rid of?

**Comment by jhallam3** [comment]
It's the black header that's got the easy chart logo.

Regards

Jon Hallam


On 3 Oct 2016, at 20:47, Thomas Daem <notifications@github.com> wrote:

Can you show (printscreen) the header you want to get rid of?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/daemth/easychart/issues/22#issuecomment-251206740>, or mute
the thread

**Comment by daemth** [comment]
You can use buildmode 'render' (https://github.com/daemth/easychart/wiki/Builds#render), this is the preferred way of working when you only want to show a chart and you don't need to edit it.

Another way to hide the header is by setting the **UIMode-option to 'viewer' ** in the app-build
(currently this is still in dev; https://github.com/daemth/easychart/tree/feature/issue-27__UIMode-option):
```javascript
var chart = new ec({
  element: document.getElementById('container'),
  dataUrl: 'data/time-series.csv',
  config: {"xAxis" : [{"type" : "datetime"}]},
  UIMode: 'viewer'
});
```

**Comment by daemth** [comment]
Hi @jhallam3,
Pull request #38 is rejected but a much more elegant way to switch between preview and editor-mode is being developed here: https://github.com/daemth/easychart/tree/issues/27.

**Comment by jhallam3** [comment]
Hi there. 

How can I get the Debug information for a chat to then save in a database to then render that setting later on. 

Ive tried 

utput.getConfig()

the result is ec.js:28503 Uncaught TypeError: Cannot read property ‘UIMode' of undefined

Thanks Jon

**Comment by jhallam3** [comment]
Hi Ive found that its getConfigStringified();

How can I get that on change, or on a save button?

**Comment by jhallam3** [comment]
var charty; 

        document.addEventListener("DOMContentLoaded", function () {

            chart = new ec({
                element: document.getElementById('container-1'),
                dataUrl: '@url'.replace("amp;", ""),
                dataTab     : true,
                debuggerTab: true,
                showLogo: false,
               
               
                

            });
            console.log(chart) 
            console.log(chart.getConfigStringified()) 
          
          charty = chart;
            

        });
