### ISSUE TITLE
Using an Easychart Field with the Paragraphs module

### ISSUE THREAD

**Issue by curtisgrife** [daemth/easychart#41]
Hello,

Not sure if this issue should be posted here or not, tried the drupal.org project issue queue and didn't hear anything back.

The site I'm developing needs to have multiple chart types per node so I decided to use the Paragraphs module so I could mix and match with other fields (ie. tablefield). I set up a paragraph bundle with a chart field in it and when I viewed the node edit form the chart field displayed twice inside the paragraph (see screen grab attached). I tried adding a chart field to a field collection and the same thing happened.

If there's anyway you could help me out with this it would be greatly appreciated. Please let me know if any other info is needed.

<img width="1086" alt="easychart_paragraphs" src="https://cloud.githubusercontent.com/assets/5530154/18714986/88a43636-7fe5-11e6-8b71-dfe30c5ebf49.png">

**Comment by daemth** [comment]
Sorry it took so long!
We'll look into this here: https://www.drupal.org/node/2798869

**Comment by curtisgrife** [comment]
No problem! Thanks again.
