### ISSUE TITLE
Pie Chart (donut) with centered title.

### ISSUE THREAD

**Issue by daemth** [daemth/easychart#42]
Is there a way to put the title of a donut chart in the center of the donut rather than at the top?
Similarly, what about a value from the table as a label in the center of the donut (e.g. show the value from cell C8 as text in the middle of the donut)?

(original issue: https://www.drupal.org/node/2724285 by @ryantollefson)

**Comment by daemth** [comment]
http://codepen.io/thomas_rz/pen/vXyoaK?editors=1010

**Comment by frankbaele** [comment]
no response, closing

**Comment by ryantollefson** [comment]
Sorry for the late response, yes, that's what I was thinking.
