### ISSUE TITLE
How to...

### ISSUE THREAD

**Issue by jhallam3** [daemth/easychart#58]
Hi there. 

I have the below data. 

I want to show the graph grouped on the date, with on that day there was high medium and low numbers. 

Please can you advise how I can do this please? 

Thanks in advance. 

```
	, Count	 Date
 High	 16	 2016-10-03
 Medium	 14	 2016-10-03
 Low	 20	 2016-10-03
 High	 19	 2016-10-04
 Medium	 17	 2016-10-04
 Low	 12	 2016-10-04
 High	 22	 2016-10-05
 Medium	 15	 2016-10-05
 Low	 20	 2016-10-05
 High	 20	 2016-10-06
 Medium	 12	 2016-10-06
 Low	 14	 2016-10-06
 High	 9	 2016-10-07
 Medium	 16	 2016-10-07
 Low	 21	 2016-10-07
 High	 21	 2016-10-10
 Medium	 15	 2016-10-10
 Low	 25	 2016-10-10

```

**Comment by daemth** [comment]
This is more like a basic Highcharts-question, nevertheless I'd like to share my opinion with you. ;-)
This is how I would structure your data:
```
	high	medium	low
2016-10-03	16	14	20
2016-10-04	19	17	12
2016-10-05	22	15	20
2016-10-06	20	12	14
2016-10-07	9	16	21
2016-10-10	21	15	25
```

in customise tab:
chart settings > type > **column**
axes > x axis 1 > type > **datetime**

this results in a chart like: http://easychart.org/issues/58

interesting further reading material: http://www.highcharts.com/docs/chart-concepts/understanding-highcharts

Kind regards,
Thomas
