### ISSUE TITLE
Setting high of chart 

### ISSUE THREAD

**Issue by jhallam3** [daemth/easychart#60]
Hi is there a way of doing this? 

Ive got multiple charts on a page, some have to be bigger that others etc

**Comment by daemth** [comment]
You mean like styling the chart containers css-wise?

**Comment by jhallam3** [comment]
yeh I think so  

seeing the chart hight. 

Ive investigated future and setting hight: xxx in the 
chart element in the debug out makes it work. I cant see how to apply the hight variable inside that chart element 

hope that makes sense

**Comment by jhallam3** [comment]
Ive done this and works well. 

if(!configdata.chart.height){
                configdata.chart.height = 100;
        }
        else{
               
        }

**Comment by daemth** [comment]
Great!

**Comment by jhallam3** [comment]
HI any update on keeping the title fixed with changing chart type? Thanks

Regards

Jon Hallam


On 14 Oct 2016, at 15:09, Thomas Daem <notifications@github.com> wrote:

Great!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/daemth/easychart/issues/60#issuecomment-253810564>, or mute
the thread
