### ISSUE TITLE
Is it possible to integrate into TinyMCE without drupal?

### ISSUE THREAD

**Issue by thewhiterabbit** [daemth/easychart#62]
I guess what I'm asking is does this have a standalone plugin for TinyMCE?

**Comment by jyve** [comment]
We currently do not have a standalone plugin for TinyMCE, sorry.

2016-10-26 22:20 GMT+02:00 Vague Rabbit <notifications@github.com>:

**Comment by daemth** [comment]
Hi @thewhiterabbit,

As @jyve said, we don't have a standalone plugin for TinyMCE.
But I do have some good news for you: @highcharts recently released a public beta version of their own editor, at last. :-) (https://github.com/highcharts/highcharts-editor).
Best of all is, they have a TinyMCE integration: http://editor.highcharts.com/tinymce.html.

All the best,
Thomas
